/*---------------------------------------------------------------------------+
| Imakefile for dynamag
+---------------------------------------------------------------------------*/
DEPLIBS = 
LOCAL_LIBRARIES = XawClientLibs 
SYS_LIBRARIES = -lm
SRCS = dynamag.c
OBJS = dynamag.o
CC = cc
ComplexProgramTarget(dynamag)
